application:    mip-dashboard
version:        1
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /css
          static_dir: public/css
          application_readable: true

        - url: /fonts
          static_dir: public/fonts
          application_readable: true

        - url: /scripts
          static_dir: public/scripts
          application_readable: true

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
        - ^(.*/)?\.DS_Store$

env_variables:
        GAE_SKIP_GCS_INIT: false