application: mip-dashboard
runtime: python27
api_version: 1
threadsafe: false

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /scripts
  static_dir: scripts

- url: /.*
  script: dashboard.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
