application: mip-dashboard
runtime: python27
api_version: 1
threadsafe: true
module: stage-cron
version: stage

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    script: main.app
    login: admin

libraries:
  - name: MySQLdb
    version: "latest"

skip_files:
  - ^(env/.*)
  - ^(.*/)?.*\.py[co]$
