application: mip-dashboard
runtime: python27
api_version: 1
threadsafe: true
module: etl
version: demo

manual_scaling:
  instances: 1

handlers:
- url: /hive
  static_dir: hive
  application_readable: true
  login: admin
- url: /.*
  script: job.app
  login: admin

libraries:
- name: MySQLdb
  version: "latest"