application: mip-dashboard
runtime: python27
api_version: 1
threadsafe: true
module: etl
version: demo

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    script: job.app
    login: admin

libraries:
  - name: MySQLdb
    version: "latest"

skip_files:
  - ^(env/.*)
