class mysql:
	data_users = ('''INSERT INTO `data_users_{dimension}`( '''
		''' `date`, `client_id`, `TotalMembersThisWeek`,`KPI_TotalMembersKnownToMIP`,`CameToSiteThroughEmail`,`KPI_TotalEmailSubscribersKnownToMIP`,`KPI_PercentKnownSubsWhoCame`,`NewEmailSubscribers`,`TotalDonorsThisWeek`,`KPI_TotalDonorsKnownToMIP`,`Duplicated_CameThroughEmailPlusDonors`,`Unduplicated_TotalUsersKPI`,`Duplicated_Database_CameThroughEmailPlusDonors`,`Unduplicated_Database_TotalUsersKPI` '''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		''' `TotalMembersThisWeek` = %s, `KPI_TotalMembersKnownToMIP` = %s, `CameToSiteThroughEmail` = %s, `KPI_TotalEmailSubscribersKnownToMIP` = %s, `KPI_PercentKnownSubsWhoCame` = %s, `NewEmailSubscribers` = %s, `TotalDonorsThisWeek` = %s, `KPI_TotalDonorsKnownToMIP` = %s, `Duplicated_CameThroughEmailPlusDonors` = %s, `Unduplicated_TotalUsersKPI` = %s, `Duplicated_Database_CameThroughEmailPlusDonors` = %s, `Unduplicated_Database_TotalUsersKPI` = %s''')
	data_stories = ('''INSERT INTO `data_stories_{dimension}`( '''
		'''`date`, `path_md5`, `client_id`, `Page_Path`, `Pageviews`, `Scroll_Start`, `Scroll_25`, `Scroll_50`, `Scroll_75`, `Scroll_100`, `Scroll_Supplemental`, `Scroll_End`, `Time_15`, `Time_30`, `Time_45`, `Time_60`, `Time_75`, `Time_90`, `Comments`, `Emails`, `Tweets`, `Facebook_Recommendations`, `Related_Clicks`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''`Page_Path` = %s, `Pageviews` = %s, `Scroll_Start` = %s, `Scroll_25` = %s, `Scroll_50` = %s, `Scroll_75` = %s, `Scroll_100` = %s, `Scroll_Supplemental` = %s, `Scroll_End` = %s, `Time_15` = %s, `Time_30` = %s, `Time_45` = %s, `Time_60` = %s, `Time_75` = %s, `Time_90` = %s, `Comments` = %s, `Emails` = %s, `Tweets` = %s, `Facebook_Recommendations` = %s, `Related_Clicks` = %s ''')
	data_quality = ('''INSERT INTO `data_quality_new_{dimension}`( '''
		'''`date`, `client_id`, `GA_Users`, `MIP_Users`, `Came_To_Site_Subscribed_And_Came_Through_Email`, `Came_To_Site_Came_Through_Email_For_First_Time`, `Came_To_Site_Came_Through_Email_Again`, `Came_To_Site_Total_Came_To_Site_Through_Email`, `New_Subscribers_Subscribed_And_Came_Through_Email`, `New_Subscribers_Subscribed_Only`, `New_Subscribers_KPI_New_Email_Subscribers`, `Known_To_MIP_New_Email_Subscribers`, `Known_To_MIP_Came_Through_Email_For_First_Time`, `Known_To_MIP_Came_Through_Email_Again`, `Known_To_MIP_Subscribers_Who_Did_Not_Come_Through_Email`, `Known_To_MIP_KPI_Total_Email_Subscribers_Known_To_MIP`, `Known_To_MIP_KPI_Percent_Known_Subs_Who_Came`, `Donated_This_Week_New_Donors`, `Donated_This_Week_Donated_Again`, `Donated_This_Week_Total_Donors_This_Week`, `Known_To_MIP_New_Donors`, `Known_To_MIP_Donated_Again`, `Known_To_MIP_Database_Donors_Who_Did_Not_Donate_This_Week`, `Known_To_MIP_KPI_Total_Donors_Known_To_MIP`, `Known_To_MIP_KPI_Percent_Known_Donors_Who_Donated`, `Email_Newsletter_Clicks`, `Totol_Donors_This_Week`, `Logged_In_This_Week_New_Logins`, `Logged_In_This_Week_Logged_In_Again`, `Logged_In_This_Week_Total_Logins_This_Week`, `Known_To_MIP_New_Logins`, `Known_To_MIP_Logged_In_Again`, `Known_To_MIP_Database_Members_Who_Did_Not_Login_This_Week`, `Known_To_MIP_KPI_Total_Members_Known_To_MIP`, `Known_To_MIP_KPI_Percent_Known_Members_Who_Logged_In`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''`GA_Users` = %s, `MIP_Users` = %s, `Came_To_Site_Subscribed_And_Came_Through_Email` = %s, `Came_To_Site_Came_Through_Email_For_First_Time` = %s, `Came_To_Site_Came_Through_Email_Again` = %s, `Came_To_Site_Total_Came_To_Site_Through_Email` = %s, `New_Subscribers_Subscribed_And_Came_Through_Email` = %s, `New_Subscribers_Subscribed_Only` = %s, `New_Subscribers_KPI_New_Email_Subscribers` = %s, `Known_To_MIP_New_Email_Subscribers` = %s, `Known_To_MIP_Came_Through_Email_For_First_Time` = %s, `Known_To_MIP_Came_Through_Email_Again` = %s, `Known_To_MIP_Subscribers_Who_Did_Not_Come_Through_Email` = %s, `Known_To_MIP_KPI_Total_Email_Subscribers_Known_To_MIP` = %s, `Known_To_MIP_KPI_Percent_Known_Subs_Who_Came` = %s, `Donated_This_Week_New_Donors` = %s, `Donated_This_Week_Donated_Again` = %s, `Donated_This_Week_Total_Donors_This_Week` = %s, `Known_To_MIP_New_Donors` = %s, `Known_To_MIP_Donated_Again` = %s, `Known_To_MIP_Database_Donors_Who_Did_Not_Donate_This_Week` = %s, `Known_To_MIP_KPI_Total_Donors_Known_To_MIP` = %s, `Known_To_MIP_KPI_Percent_Known_Donors_Who_Donated` = %s, `Email_Newsletter_Clicks` = %s, `Totol_Donors_This_Week` = %s, `Logged_In_This_Week_New_Logins` = %s, `Logged_In_This_Week_Logged_In_Again` = %s, `Logged_In_This_Week_Total_Logins_This_Week` = %s, `Known_To_MIP_New_Logins` = %s, `Known_To_MIP_Logged_In_Again` = %s, `Known_To_MIP_Database_Members_Who_Did_Not_Login_This_Week` = %s, `Known_To_MIP_KPI_Total_Members_Known_To_MIP` = %s, `Known_To_MIP_KPI_Percent_Known_Members_Who_Logged_In` = %s''')