class mysql:
	data_users = ('''INSERT INTO `data_users_{dimension}`( '''
		''' `date`, `client_id`, `totalmembersthisweek`, `kpi_totalmembersknowntomip`, `cametositethroughemail`, `kpi_totalemailsubscribersknowntomip`, `kpi_percentknownsubswhocame`, `kpi_newemailsubscribers`, `totaldonorsthisweek`, `kpi_totaldonorsknowntomip`, `duplicated_memberspluscamethroughemailplusdonors`, `unduplicated_totaluserskpi`, `duplicated_database_memberspluscamethroughemailplusdonors`, `unduplicated_database_totaluserskpi` '''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		''' `totalmembersthisweek` = %s, `kpi_totalmembersknowntomip` = %s, `cametositethroughemail` = %s, `kpi_totalemailsubscribersknowntomip` = %s, `kpi_percentknownsubswhocame` = %s, `kpi_newemailsubscribers` = %s, `totaldonorsthisweek` = %s, `kpi_totaldonorsknowntomip` = %s, `duplicated_memberspluscamethroughemailplusdonors` = %s, `unduplicated_totaluserskpi` = %s, `duplicated_database_memberspluscamethroughemailplusdonors` = %s, `unduplicated_database_totaluserskpi` = %s''')
	data_stories = ('''INSERT INTO `data_stories_{dimension}`( '''
		'''`date`, `path_md5`, `client_id`, `page_path`,`pageviews`,`scroll_start`,`scroll_25`,`scroll_50`,`scroll_75`,`scroll_100`,`scroll_supplemental`,`scroll_end`,`time_15`,`time_30`,`time_45`,`time_60`,`time_75`,`time_90`,`comments`,`emails`,`tweets`,`facebook_recommendations`,`related_clicks`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''`page_path` = %s, `pageviews` = %s, `scroll_start` = %s, `scroll_25` = %s, `scroll_50` = %s, `scroll_75` = %s, `scroll_100` = %s, `scroll_supplemental` = %s, `scroll_end` = %s, `time_15` = %s, `time_30` = %s, `time_45` = %s, `time_60` = %s, `time_75` = %s, `time_90` = %s, `comments` = %s, `emails` = %s, `tweets` = %s, `facebook_recommendations` = %s, `related_clicks` = %s''')
	data_quality = ('''INSERT INTO `data_quality_new_{dimension}`( '''
		'''`date`, `client_id`, `ga_users`, `mip_users`, `subscribedandcamethroughemail`, `camethroughemailforfirsttime`, `camethroughemailagain`, `total_cametositethroughemail`, `subscribedandcamethroughemail2`, `subscribedonly`, `kpi_newemailsubscribers`, `kpi_newemailsubscribers2`, `camethroughemailforfirsttime2`, `camethroughemailagain2`, `subscriberswhodidnotcomethroughemail`, `kpi_totalemailsubscribersknowntomip`, `kpi_percentknownsubswhocame`, `newdonors`, `donatedagain`, `totaldonorsthisweek`, `newdonors2`, `donatedagain2`, `databasedonorswhodidnotdonatethisweek`, `kpi_totaldonorsknowntomip`, `kpi_percentknowndonorswhodonated`, `newlogins`, `loggedinagain`, `totalloginsthisweek`, `newlogins2`, `loggedinagain2`, `databasememberswhodidnotloginthisweek`, `kpi_totalmembersknowntomip`, `kpi_percentknownmemberswhologgedin`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''```ga_users` = %s, `mip_users` = %s, `subscribedandcamethroughemail` = %s, `camethroughemailforfirsttime` = %s, `camethroughemailagain` = %s, `total_cametositethroughemail` = %s, `subscribedandcamethroughemail2` = %s, `subscribedonly` = %s, `kpi_newemailsubscribers` = %s, `kpi_newemailsubscribers2` = %s, `camethroughemailforfirsttime2` = %s, `camethroughemailagain2` = %s, `subscriberswhodidnotcomethroughemail` = %s, `kpi_totalemailsubscribersknowntomip` = %s, `kpi_percentknownsubswhocame` = %s, `newdonors` = %s, `donatedagain` = %s, `totaldonorsthisweek` = %s, `newdonors2` = %s, `donatedagain2` = %s, `databasedonorswhodidnotdonatethisweek` = %s, `kpi_totaldonorsknowntomip` = %s, `kpi_percentknowndonorswhodonated` = %s, `newlogins` = %s, `loggedinagain` = %s, `totalloginsthisweek` = %s, `newlogins2` = %s, `loggedinagain2` = %s, `databasememberswhodidnotloginthisweek` = %s, `kpi_totalmembersknowntomip` = %s, `kpi_percentknownmemberswhologgedin` = %s''')