class mysql:
	data_users = ('''INSERT INTO `data_users_{dimension}`( '''
		''' `date`, `client_id`, `totalmembersthisweek`, `kpi_totalmembersknowntomip`, `cametositethroughemail`, `kpi_totalemailsubscribersknowntomip`, `kpi_percentknownsubswhocame`, `kpi_newemailsubscribers`, `totaldonorsthisweek`, `kpi_totaldonorsknowntomip`, `duplicated_memberspluscamethroughemailplusdonors`, `unduplicated_totaluserskpi`, `duplicated_database_memberspluscamethroughemailplusdonors`, `unduplicated_database_totaluserskpi` '''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		''' `totalmembersthisweek` = %s, `kpi_totalmembersknowntomip` = %s, `cametositethroughemail` = %s, `kpi_totalemailsubscribersknowntomip` = %s, `kpi_percentknownsubswhocame` = %s, `kpi_newemailsubscribers` = %s, `totaldonorsthisweek` = %s, `kpi_totaldonorsknowntomip` = %s, `duplicated_memberspluscamethroughemailplusdonors` = %s, `unduplicated_totaluserskpi` = %s, `duplicated_database_memberspluscamethroughemailplusdonors` = %s, `unduplicated_database_totaluserskpi` = %s''')
	data_stories = ('''INSERT INTO `data_stories`( '''
		'''`path_md5`, `client_id`, `page_path`,`pageviews`,`scroll_start`,`scroll_25`,`scroll_50`,`scroll_75`,`scroll_100`,`scroll_supplemental`,`scroll_end`,`time_15`,`time_30`,`time_45`,`time_60`,`time_75`,`time_90`,`comments`,`emails`,`tweets`,`facebook_recommendations`,`related_clicks`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''`page_path` = %s, `pageviews` = %s, `scroll_start` = %s, `scroll_25` = %s, `scroll_50` = %s, `scroll_75` = %s, `scroll_100` = %s, `scroll_supplemental` = %s, `scroll_end` = %s, `time_15` = %s, `time_30` = %s, `time_45` = %s, `time_60` = %s, `time_75` = %s, `time_90` = %s, `comments` = %s, `emails` = %s, `tweets` = %s, `facebook_recommendations` = %s, `related_clicks` = %s''')
	data_quality = ('''INSERT INTO `data_quality_{dimension}`( '''
		'''`date`, `client_id`, `events`, `ga_users`, `mip_users`, `user_variance`, `identified_emailsubscribers`, `known_emailsubscribers`,  `total_database_emails`, `identified_newemailsubscribers`, `email_newsletter_clicks`, `eloqua_email_newsletter_clicks`, `email_newsletter_clicks_variance`,  `identified_donors`, `known_donors`, `eloqua_known_donors`, `donors_variance`, `total_known_donors`, `total_known__unique_email`'''
		''') VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) '''
		''' ON DUPLICATE KEY UPDATE '''
		'''`events`=%s, `ga_users`=%s, `mip_users`=%s, `user_variance`=%s, `identified_emailsubscribers`=%s, `known_emailsubscribers`=%s, `total_database_emails`=%s, `identified_newemailsubscribers`=%s, `email_newsletter_clicks`=%s, `eloqua_email_newsletter_clicks`=%s, `email_newsletter_clicks_variance`=%s, `identified_donors`=%s, `known_donors`=%s, `eloqua_known_donors`=%s, `donors_variance`=%s, `total_known_donors`=%s, `total_known__unique_email`=%s''')